<?php

/**
 * @file
 * Provides the popup functionality.
 */

/**
 * Implements hook_block_info().
 */
function pb_popup_block_info() {
  $blocks = array();

  $blocks['pb_popup'] = array(
    'info' => t('Popup Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => TRUE,
    'region' => 'content',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pb_popup_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'pb_popup':
      libraries_load('jstorage');
      $block['subject'] = NULL;
      // Create markup and content.
      $output = '';
      $output .= '<div class="pb-popup__wrapper">';
      $output .= '<div class="pb-popup__date">' . t('UNTIL THE 25th OF JULY 2018') . '</div>';
      $output .= '<div class="pb-popup__percentage">-30%</div>';
      $output .= '<div class="pb-popup__content">' . t('With every <strong>face sunscreen</strong><br /> 30% discount to <strong>body sunscreen</strong>') . '</div>';
      $output .= '<div class="pb-popup__button">' . l(t('SEE THE FACE SUNSCREENS'), base_path() . 'taxonomy/term/14') . '</div>';
      $output .= '</div>';
      $block['content'] = array(
        '#markup' => $output,
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'pb_popup') . '/css/pb_popup.css',
          ),
          'js' => array(
            drupal_get_path('module', 'pb_popup') . '/js/pb_popup.js',
          )
        ),
      );
      break;
  }
  return $block;
}
